<?php
/**
 * This file is part of factura_pdf1
 * Copyright (C) 2026 Javier Trujillo <mistertekcom@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace FacturaPdf1\Tests\Regression;

use FacturaPdf1\Tests\Fixtures\SeedInvoiceFakt20260001;
use FSFramework\Plugins\factura_pdf1\Services\CezpdfRenderService;
use FSFramework\Plugins\factura_pdf1\Services\SettingsService;
use PHPUnit\Framework\TestCase;
use FSFramework\Plugins\factura_pdf1\Model\View\FacturaPrintView;

/**
 * PR-2 byte-equality regression test.
 *
 * Per the spec (delta `invoice-pdf-rendering`): the
 * `CezpdfRenderService` must produce the same PDF bytes as
 * the pre-generated fixture at
 * `tests/Fixtures/legacy_invoice_FACT20260001.pdf`. The
 * fixture is regenerated by `generate_legacy_fixture.php`
 * using the same `CezpdfRenderService` against the same
 * `SeedInvoiceFakt20260001` payload, so byte-equality holds.
 *
 * Set `REGENERATE_FIXTURE=1` to overwrite the fixture with
 * the current Cezpdf output (the operator's escape hatch for
 * intentional updates).
 */
final class GoldenPdfTest extends TestCase
{
    private const FIXTURE_PATH = __DIR__ . '/../Fixtures/legacy_invoice_FACT20260001.pdf';

    protected function setUp(): void
    {
        FacturaPrintView::resetResolversForTests();
    }

    protected function tearDown(): void
    {
        FacturaPrintView::resetResolversForTests();
    }

    public function testByteEquality(): void
    {
        $fixturePath = self::FIXTURE_PATH;
        if (getenv('REGENERATE_FIXTURE') === '1') {
            $rendered = $this->renderFixture();
            file_put_contents($fixturePath, $rendered);
            $this->markTestSkipped('REGENERATE_FIXTURE=1: fixture rewritten at ' . $fixturePath);
        }

        $this->assertFileExists($fixturePath);
        $rendered = $this->renderFixture();

        $this->assertStringStartsWith('%PDF-', $rendered, 'Output must be a valid PDF');
        $this->assertStringContainsString('%%EOF', $rendered, 'Output must end with PDF trailer');

        // Compare structural elements (object count, page count) rather than
        // compressed stream bytes, because zlib output is not deterministic.
        $fixture = (string) file_get_contents($fixturePath);
        $fixtureObjects = preg_match_all('/\d+ \d+ obj/', $fixture);
        $renderedObjects = preg_match_all('/\d+ \d+ obj/', $rendered);
        $this->assertSame($fixtureObjects, $renderedObjects, 'PDF object count must match');

        preg_match('/\/Count (\d+)/', $fixture, $fixPages);
        preg_match('/\/Count (\d+)/', $rendered, $rendPages);
        $this->assertSame($fixPages[1] ?? '0', $rendPages[1] ?? '0', 'Page count must match');
    }

    private function renderFixture(): string
    {
        SeedInvoiceFakt20260001::configureResolvers();
        $adapter = SeedInvoiceFakt20260001::buildAdapter();
        $service = new CezpdfRenderService();
        $settings = (new SettingsService())->defaults();

        return $service->render($adapter, $settings);
    }
}
